compilation error for pike 9.1
* Assigning 0 to a string causes an error
* Silence some warnings by accessing methods with '->'
* "$" did not need escaping
* Some warnings for popen() will be addressed later

ed.pike:85: Warning: Calling a deprecated value.
ed.pike:85: Warning: Using deprecated { FILE = object(implements Stdio.FILE) } value.
ed.pike:150: Warning: Calling a deprecated value.
ed.pike:150: Warning: Using deprecated { FILE = object(implements Stdio.FILE) } value.
ed.pike:453: Warning: Calling a deprecated value.
ed.pike:453: Warning: Using deprecated { FILE = object(implements Stdio.FILE) } value.
ed.pike:629: Warning: Calling a deprecated value.
ed.pike:629: Warning: Using deprecated string value.